name: CI
on:
  push:
    branches: [ "main" ]
    tags:
      - '**'
  pull_request:
    branches: [ "main" ]
    tags:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo "GitHub Ref is: ${{ github.ref }}"  
          echo "GitHub Ref Type is: ${{ github.ref_type }}"  
          echo "GitHub Event Ref is: ${{ github.event.ref }}" 
          echo "GitHub Tag is: ${{ steps.meta.outputs.tags }}" 
